export default {
	engineLogoOn: true,
	enginelogoon: true,
	info: {
		browseService: false,
		buttonOptions: {
			comment: false,
			headerLink: true,
			hideAll: false,
			hideHeader: false,
			share: false
		},
		closeMusic: false,
		contact: {
			contactAddress: "",
			contactEmail: "admin@qq.com",
			contactName: "admin",
			contactPhone: "",
			externalUrl: null,
			headimgurl: "",
			userId: "",
			wxQrcode: null
		},
		custService: false,
		custServiceCode: null,
		customLogo: null,
		descFlag: false,
		description: "",
		durationEndTs: null,
		enLang: false,
		extobjs: [],
		floor: 1,
		hideLogo: false,
		liveService: false,
		loadingThumb: null,
		loadingVideo: null,
		lupt: 0,
		lut: null,
		lutName: null,
		lutid: null,
		lutsz: null,
		minimap: {
			mapImage: "",
			mapName: "minimap",
			position: {
				x: 0,
				y: 0
			},
			rect: 86,
			show: true
		},
		mobileThumb: "",
		modelRotate: false,
		musicAutoPlay: true,
		musicFile: "",
		musicId: null,
		musicName: "",
		myBrowseService: false,
		myCustService: false,
		name: "name",
		panoImg: null,
		password: "111111",
		pluginFlag: false,
		renderOver: false,
		sceneId: "",
		sceneShare: null,
		sceneTemplateLive: {
			liveEndTime: null,
			liveOpenType: 0,
			liveStartTime: null,
			liveState: false,
			liveUrl: null,
			senceTemplateId: null
		},
		scripts: [],
		showDescFlag: 0,
		startCamera: "",
		tempid: "",
		thumb: "",
		titleFlag: true,
		token: null,
		typeId: "",
		usePwd: false,
		useThumbLoading: true,
		username: "",
		viewCount: 0
	}
}
